# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e55b7af32669422967ea10f99cd6128aa27eaac2fd15f41ba35685a0942c9e03f7321ca54f3da1f1a544e8ad8e421e8bf21455618694972e0ab8e73f9f12c25c

test:
  secret_key_base: c46e62fbd48cec5ee98eafdd9951e4ab43d3fcbb33a260623700f6f7cb6ab4b2ffdfcbc04f4b5d146c41bc6316bf402cff2caba73f71ccb8cceddd8fbc1963f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
